# Generated by Django 3.2 on 2022-04-18 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=100)),
                ('NumMembers', models.IntegerField(default=1)),
                ('IsActive', models.BooleanField(default=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('HeightFeet', models.IntegerField(blank=1, null=True)),
                ('HeightInches', models.IntegerField(blank=1, null=True)),
                ('Weight', models.FloatField(blank=1, null=True)),
                ('Gender', models.CharField(blank=1, max_length=20, null=True)),
                ('UserSteps', models.IntegerField(blank=1, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeOfRequest', models.DateTimeField()),
                ('Status', models.CharField(choices=[('R', 'Request'), ('I', 'Invite')], max_length=1, null=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.group')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupJoinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateJoined', models.DateTimeField(default=datetime.datetime(2022, 4, 18, 18, 28, 29, 533600))),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.group')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetalsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReachedUserGoal', models.BooleanField(default=False)),
                ('FirstSteps', models.BooleanField(default=False)),
                ('StepsTaken', models.BooleanField(default=False)),
                ('Over6Months', models.BooleanField(default=False)),
                ('Powerhouse', models.BooleanField(default=False)),
                ('TeamWork', models.BooleanField(default=False)),
                ('Teamleader', models.BooleanField(default=False)),
                ('ReachedTeamGoal', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAndTime', models.DateTimeField(default=datetime.datetime(2022, 4, 18, 18, 28, 29, 532611), null=True)),
                ('RatingOfDay', models.IntegerField(blank=1, null=True)),
                ('StepsTaken', models.IntegerField(blank=1, null=True)),
                ('HoursSitting', models.FloatField(blank=1, null=True)),
                ('HoursSlept', models.FloatField(blank=1, null=True)),
                ('WorkedOut', models.BooleanField(blank=1, default=None, null=True)),
                ('LengthOfWorkout', models.FloatField(blank=1, null=True)),
                ('IntensityOfWorkout', models.IntegerField(blank=1, null=True)),
                ('MealsEaten', models.IntegerField(blank=1, null=True)),
                ('SnacksEaten', models.IntegerField(blank=1, null=True)),
                ('FoodHealth', models.FloatField(blank=1, null=True)),
                ('CigarettesSmoked', models.IntegerField(blank=1, null=True)),
                ('AlcoholicDrinks', models.IntegerField(blank=1, null=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSent', models.DateTimeField(default=datetime.datetime(2022, 4, 18, 18, 28, 29, 532074))),
                ('MessageTitle', models.CharField(max_length=100, null=True)),
                ('MessageBody', models.CharField(max_length=5000, null=True)),
                ('Recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recipient', to=settings.AUTH_USER_MODEL)),
                ('Sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
