# Generated by Django 3.2 on 2022-03-08 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=100)),
                ('NumMembers', models.IntegerField(default=0)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateTimeField(blank=1)),
                ('HeightFeet', models.IntegerField(blank=1)),
                ('HeightInches', models.IntegerField(blank=1)),
                ('Weight', models.FloatField(blank=1)),
                ('Gender', models.CharField(blank=1, max_length=20)),
                ('IsActive', models.BooleanField(blank=1, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeOfRequest', models.DateTimeField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.group')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupJoinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateJoined', models.DateTimeField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.group')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSent', models.DateTimeField()),
                ('MessageTitle', models.CharField(max_length=100)),
                ('MessageBody', models.CharField(max_length=5000)),
                ('Recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipient', to='frontpage.user')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='frontpage.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.user'),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAndTime', models.DateTimeField()),
                ('RatingOfDay', models.IntegerField(blank=1)),
                ('StepsTaken', models.IntegerField(blank=1)),
                ('HoursSitting', models.FloatField(blank=1)),
                ('HoursSlept', models.FloatField(blank=1)),
                ('WorkedOut', models.BooleanField(blank=1)),
                ('LengthOfWorkout', models.FloatField(blank=1)),
                ('IntensityOfWorkout', models.IntegerField(blank=1)),
                ('MealsEaten', models.IntegerField(blank=1)),
                ('SnacksEaten', models.IntegerField(blank=1)),
                ('FoodHealth', models.FloatField(blank=1)),
                ('CigarettesSmoked', models.IntegerField(blank=1)),
                ('AlcoholicDrinks', models.IntegerField(blank=1)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.user')),
            ],
        ),
    ]
