# Generated by Django 3.2 on 2022-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20220316_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='DateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
