# Generated by Django 3.2 on 2022-03-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_userinfo_dateofbirth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
