# Generated by Django 3.2 on 2022-03-16 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontpage', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('HeightFeet', models.IntegerField(blank=1, null=True)),
                ('HeightInches', models.IntegerField(blank=1, null=True)),
                ('Weight', models.FloatField(blank=1, null=True)),
                ('Gender', models.CharField(blank=1, max_length=20, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
